<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'The access to the content provided through this website is free. Using the features of this site require pre-registration, which will require an ID and password for the user.' =>
    'El acceso a los contenidos proporcionados a través del presente sitio web tiene carácter gratuito. La utilización de las funcionalidades del sitio requieren registro previo, lo cual requerirá la selección por parte del usuario de un identificador y contraseña.',
  'Applicable law' =>
    'Legislación aplicable',
  'Conditions of Use and Navigation' =>
    'Condiciones de Uso y Navegación',
  'Data Controller' =>
    'Responsable del fichero',
  'Data collection and processing purposes:' =>
    'Recogida de datos y finalidades de tratamiento:',
  'Data communication' =>
    'Comunicación de datos',
  'Data holder will not be communicated to third parties in any case. If for some reason necessary to communicate such data to third parties, such a case will be communicated in advance to the owner of the data, specifying the purpose of the communication and the third who will be communicated.' =>
    'Los datos de los titulares no serán comunicados a terceros en ningún caso. Si por alguna razón fuera necesario comunicar dichos datos a terceros, dicho supuesto le será comunicado con carácter previo al titular de los datos, especificando las finalidades de la comunicación y el tercero a quien van a ser comunicados.',
  'Disclaimer' =>
    'Aviso Legal',
  'Disclaimer and Conditions of Use' =>
    'Aviso Legal y Consiciones de Uso',
  'For cases where the regulations provide for the possibility of undergoing a particular jurisdiction, and the user Cohaerentis Consultants submitted their disputes, expressly waiving any other jurisdiction that may apply to the courts of Madrid Capital resignation.' =>
    'Para los supuestos en que la normativa prevea la posibilidad de someterse a un fuero concreto, Cohaerentis Consultores y el usuario someterán sus controversias, con renuncia expresa a cualquier otro foro que pudiera corresponderles, a los juzgados y tribunales de Madrid capital.',
  'Google Analytics' =>
    'Google Analytics',
  'If you require legal advice please contact us for this purpose.' =>
    'Si requiere asesoramiento jurídico póngase en contacto con nosotros a tal efecto.',
  'In case of lost password, users must communicate the issue to the webmaster to proceed to the immediate cancellation of it.' =>
    'En caso de pérdida de la contraseña, el usuario debe comunicar dicha cuestión a los webmaster para proceder a la inmediata cancelación de la misma.',
  'Intellectual and industrial property' =>
    'Propiedad intelectual e industrial',
  'Limitation of Liability' =>
    'Limitación de Responsabilidad',
  'Navigation' =>
    'Navegación',
  'Opening hours to public from 10 to 14.00 and from 15.30 to 18.00' =>
    'Horario de atención al público. De 10 a 14.00 y de 15.30 a 18.00.',
  'Professional activity' =>
    'Actividad Profesional',
  'Protection of personal data' =>
    'Protección de datos de carácter personal',
  'Cohaerentis S.L. has taken appropriate technical and organizational measures, in accordance with data protection legislation, to prevent the loss of personal data or misuse thereof.' =>
    'Cohaerentis S.L. ha adoptado las adecuadas medidas técnicas y organizativas, de conformidad con la normativa sobre protección de datos, para evitar la pérdida de datos de carácter personal o el mal uso de los mismos.',
  'Security' =>
    'Medidas de seguridad',
  'Session Cookies' =>
    'Cookies de sesión',
  'Standards and codes of conduct: ICAM regulations.' =>
    'Normas y códigos de conducta aplicables: normativa del ICAM.',
  'Telephone +34 91375 03 91.' =>
    'Teléfono +34 91375 03 91.',
  'Tell user that he can share this ofuscate link with anyone, for example its license expert consultant' =>
    'Son aplicables al ejercicio de la abogacía el Estatuto General de la Abogacía Española y el Código Deontológico.',
  'The General Statute of the Spanish Legal Profession and the Ethical Code are applicable to the practice of law.' =>
    'Son aplicables al ejercicio de la abogacía el Estatuto General de la Abogacía Española y el Código Deontológico',
  'The above personal data will be included in a file called "registered users" duly notified to the Registry of the Spanish Data Protection Agency, in compliance with the obligations under the Organic Law on Data Protection.' =>
    'Los datos personales mencionados serán incorporados en un fichero  llamado “usuarios registrados” debidamente notificado ante el Registro de la Agencia Española de Protección de Datos, en cumplimiento de las obligaciones establecidas en la Ley Orgánica de Protección de Datos.',
  'The aim of treatment is to use the web application that is available to the user.' =>
    'La finalidad de tratamiento es poder utilizar la aplicación web que se pone a disposición del usuario.',
  'The content prepared by Cohaerentis S.L. in this web site are for informational and educational purposes. These contents do not constitute legal advice or consultancy advice of any kind and may contain errors.' =>
    'Los contenidos preparados por Cohaerentis S.L. en este sitio web tienen fines informativos y divulgativos. Dichos contenidos no constituyen un asesoramiento legal o consultoría jurídica de ningún tipo y pueden contener errores.',
  'The intellectual property rights on the Web application fall under AGL v3 license and can be downloaded from the following sources' =>
    'Los derechos de propiedad intelectual sobre la aplicación web caen bajo licencia AGL v3 y los fuentes pueden descargarse del siguiente',
  'The lawyers of Cohaerentis SL belongs to Ilustre Colegio de Abogados de Madrid.' =>
    'Los abogados de Cohaerentis S.L. pertenecen al Ilustre Colegio de Abogados de Madrid.',
  'The logos used in this website are owned by Cohaerentis SL or has a license or authorization to use those signs on the portal. Use is not permitted without prior written authorization of Cohaerentis SL.' =>
    'Los signos distintivos utilizados en el portal son titularidad de Cohaerentis S.L. o posee la correspondiente licencia o autorización sobre dichos signos para usarlos en el portal. No está permitida su utilización sin autorización previa y por escrito de Cohaerentis S.L.',
  'The owner of this website is Cohaerentis S.L. with address for notifications in  Plaza del Conde del Valle de Súchil. CP. 28015. Madrid. CIF: B86107356.' =>
    'El titular de este sitio web es Cohaerentis S.L Con domicilio a efectos de notificaciones en la Plaza del Conde del Valle de Súchil. CP. 28015. Madrid. CIF: B86107356.',
  'The password must be non-transferable for each registered user. The user agrees to properly maintain custody and confidentiality of the password, without communicating it to third parties. The sole responsibility of the illegal use of user web portal for any unauthorized third party to use a password to cause loss of communication or by the user.It is responsibility of the user the use of the site by any unauthorized third party that uses the  password cause of communication or loss by the user.' =>
    'La contraseña debe ser personal e intransferible para cada usuario registrado. El usuario se compromete a mantener de manera adecuada la custodia y secreto de su contraseña de acceso, sin comunicarla a terceros. Será responsabilidad exclusiva del usuario la utilización ilícita del portal web por cualquier tercero no autorizado que utilice la contraseña a causa de la comunicación o pérdida por parte del usuario.',
  'The personal data that is collected through the domain' =>
    'Los datos de carácter personal que se recaban a través del dominio',
  'will be processed as follows:' =>
    'serán tratados con la finalidad que se indica a continuación:',
  'The relationship between the user and Cohaerentis SL shall be governed by the provisions of the existing rules on the applicable law.' =>
    'Las relaciones entre el usuario y Cohaerentis S.L. se regirán por lo dispuesto en la normativa vigente sobre la legislación aplicable.',
  'The treatment of personal data is governed by the privacy policy defined by Cohaerentis SL which can be found at this' =>
    'El tratamiento de datos de carácter personal se rige por la política de privacidad definida por Cohaerentis S.L. que puede consultarse en este',
  'The user\'s email will be used to send commercial information about the products and services of our company. Subject to the right of the user to revoke his CONSENT by the means indicated in the communication received or, in any case, writing to the following email address:' =>
    'Asimismo utilizaremos el correo electrónico del usuario para enviarle información comercial sobre los productos y servicios de nuestra empresa. Sin perjuicio del derecho del usuario a revocar su consentimiento por los medios indicados en la comunicación que reciba o, en cualquier caso, escribiendo a la siguiente dirección de correo electrónico:',
  'Therefore, the company is not responsible for the actions carried out on the basis of information obtained from this site.' =>
    'Por tanto, la empresa no se responsabiliza de las actuaciones que se lleven a cabo en función de la información obtenida en este portal.',
  'These rules are on the website of the Consejo General de la Abogacía.' =>
    'Dichas normas se encuentran en el sitio web del Consejo General de la Abogacía',
  'This site is governed by the Spanish legislation on intellectual property and applicable international law.' =>
    'El presente sitio se rige por la legislación española en materia de propiedad intelectual e industrial y por la legislación internacional aplicable',
  'This web site uses the following cookies:' =>
    'El presente sitio web utiliza las siguientes cookies:',
  'To use the web application is necessary for the user to register. On the form you will be asked for personal information relating to: name, email and company to which it belongs. Those required to provide data are marked by an asterisk.' =>
    'Para poder utilizar la aplicación web es necesario que el usuario se registre. En el formulario se le pedirán datos personales realativos a: nombre, apellidos, correo electrónico y empresa a la que pertenece. Aquellos datos que deban ser facilitados de manera obligatoria estarán marcados mediante un asterisco.',
  'Typeleft' =>
    '',
  'Typeright' =>
    '',
  'You can view files reported by Cohaerentis SL on the website of the Spanish Data Protection Agency.' =>
    'Puede consultar los ficheros notificados por Cohaerentis S.L. en la página web de la Agencia Española de Protección de Datos.',
  'You can view the owner of this website and the file manager incorporating the data collected through it in our' =>
    'Puede consultar el titular del presente Sitio web y responsable del fichero que incorporan los datos que se recaban a través del mismo en nuestro',
  'disclaimer and terms of use' =>
    'aviso legal y condiciones de uso',
  'The data controller is Cohaerentis S. L. You can view all business details in the' =>
    'El responsable del fichero es Cohaerentis S.L. Puede consultar todos los datos de la empresa en el',
  'disclaimer of this site' =>
    'aviso legal del presente sitio',
  'You can exercise your rights of access, rectification, cancellation and opposition by sending an email to' =>
    'Puede ejercitar sus derechos de acceso, rectificación, cancelación y oposición enviándonos un correo a',
  'link' =>
    'enlace',
  'repository' =>
    'repositorio',
  'Label in english' =>
    '@@Etiqueta en Español@@',
  'Legal Notice and Conditions of Use' =>
    '@@Aviso Legal y Condiciones de Uso@@',
  'About Us' =>
    'Sobre nosotros',
  'About us' =>
    'Quiénes somos',
  'Add licenses as attached files' =>
    'Añadir licencias como archivos adjuntos',
  'An error ({error}) occurs when sending confirmation email! {resend} email confirmation' =>
    'Ha ocurrido un error ({error}) al enviar el email de confirmación. {resend} el email de confirmación',
  'An error ({error}) occurs when sending remember password email!' =>
    'Ha ocurrido un error ({error}) al enviar el email de recordar la contraseña.',
  'Available Compatibilities' =>
    'Compatibilidades disponibles',
  'By pressing the “report” button you will get a full report and a link to share it.' =>
    'Al pulsar el botón de "Reporte", obtendrá un reporte completo y un enlace para compartir.',
  'Cancel' =>
    'Cancelar',
  'Change' =>
    'Cambiar',
  'Change password' =>
    'Cambiar contraseña',
  'Change your password' =>
    'Cambiar tu contraseña',
  'Company' =>
    'Compañía',
  'Compatible' =>
    'Compatible',
  'Confirmed' =>
    'Confirmado',
  'Contact' =>
    'Contacto',
  'Content' =>
    'Contenido',
  'Create' =>
    'Crear',
  'Createdate' =>
    'Fecha de creación',
  'Day' =>
    'Día',
  'Day can not be empty.' =>
    'El día no puede estar vacío',
  'Delete' =>
    'Borrar',
  'Deleted' =>
    'Borrado',
  'Description' =>
    'Descripción',
  'Design' =>
    'Diseño',
  'Dinamic' =>
    'Dinámica',
  'Disclaimer & Conditions of Use' =>
    'Aviso Legal & Condiciones de Uso',
  'Don\'t email me' =>
    'No me envíes correos',
  'Edit' =>
    'Editar',
  'Edit my profile' =>
    'Editar mi perfil',
  'Email' =>
    'Email',
  'Email Confirmation Complete' =>
    'Corfirmación de email completada',
  'Email address' =>
    'Dirección de email',
  'Email confirmation' =>
    'Confirmación de email',
  'Email confirmation has been completed succesfully.' =>
    'La confirmación del email se ha completado con éxito',
  'Email sent' =>
    'Email enviado',
  'Enabled' =>
    'Habilitado',
  'Error while changing module priority.' =>
    'Error al cambiar la prioridad del módulo',
  'Error while confirming user email' =>
    'Error al confirmar el email de usuario',
  'Error while setting new password' =>
    'Error al establecer una nueva contraseña',
  'Firstname' =>
    'Nombre',
  'Follow the instructions and click the link provided to end the registry.' =>
    'Sigue las instrucciones y pulsa el enlace para terminar el registro.',
  'Forgot your password' =>
    '¿Olvidaste la contraseña?',
  'Framework' =>
    'Framework',
  'Give access to other professionals to that inventory' =>
    'Dar acceso a otros profesionales a tu inventario',
  'Goal' =>
    'Objetivos',
  'Here we can see the compatibility of the module with the one below. The first is compare with none; the second with the first, the third with the second and with the first and so on.' =>
    'Aquí podemos ver la compatibilidad del módulo con los que están por debajo de él. El primero no se compara con ninguno. El segundo se compara con el primero. El tercero se compara con el segundo y con el primero y así sucesivamente.',
  'Here you have a list of compatible licenses to be used with your project.' =>
    'Aquí tienes una lista de licencias compatibles para que uses en tu proyecto.',
  'Hi' =>
    'Hola',
  'Home' =>
    'Inicio',
  'How do we calculate compatibility' =>
    'Cómo calculamos la compatibilidad',
  'ID' =>
    'ID',
  'Identify compatibility of licenses' =>
    'Identificar la compatibilidad de las licencias',
  'If you need help, please contact the site administrator' =>
    'Si necesitas ayuda, ponte en contacto con el administrador.',
  'In most mail programs, this should appear as a blue link which you can just click on. If that does not work, then cut and paste the address into the address line at the top of your web browser window.' =>
    'En la mayoría de los gestors de correo, debería aparecer como un enlace azul en el que pulsar. Si éste no funciona, copia y pega este enlace en la barra de direccionesm en la parte de arriba del navegador.',
  'Incompatible' =>
    'Incompatible',
  'Incorrect email or password.' =>
    'Email o contraseña incorrecta',
  'Independent application' =>
    'Aplicación independiente',
  'Integration date' =>
    'Fecha de integración',
  'Invalid code.' =>
    'Codigo invalido',
  'Keep track of the licenses being used in your code' =>
    'Hacer seguimiento de las licencias que usas en tus proyectos',
  'Label' =>
    'Etiqueta',
  'Last access' =>
    'Último acceso',
  'Lastname' =>
    'Apellidos',
  'Left' =>
    'Izquierda',
  'Library' =>
    'Librería',
  'License' =>
    'Licencia',
  'License Issues' =>
    'Problemas con la licencia',
  'Licenseother' =>
    'Otra licencia',
  'Licenses' =>
    'Licencias',
  'Licensium is a tool for preparing inventories of open source licenses, in order to control their compatibility and their requirements.' =>
    'Licensium es un aplicación para preparar inventarios de licencias open source, para tener un control de sus compatibilidades y requerimientos.',
  'Licensium has been developed by Cohaerentis, strategic consultanting based in information technologies, thanks to the collaborative effort between legal area and the business technology projects management.' =>
    'Licensium ha sido desarrollada por Cohaerentis, consultora estratégica de negocios basados en tecnologías de la información, fruto de la colaboración del área legal y de dirección de proyectos tecnológicos',
  'Licensium is a Cohaerentis Consultores product, strategic business consulting for open business models. &copy; 2014' =>
    'Licensium es un producto de Cohaerentis Consultores, Consultoría Estrategica de Negocios para modelos de negocio abiertos.&copy; 2014',
  'Link the source code used in your project' =>
    'Enlazar el código fuente integrado en su proyecto',
  'Login' =>
    'Acceder',
  'Maintain an inventory of licenses used' =>
    'Llevar un inventario de las licencias empleadas',
  'May be your memory is getting worse or perhaps your fingers are too fat...' =>
    'Tal vez tu memoria está empeorando o puede que tus dedos sean demasiado gordos...',
  'Modify date' =>
    'Fecha de modificación',
  'Module' =>
    'Módulo',
  'Module "{name}" created. This module has now the lower priority. To change it, use the arrows placed in each module. ' =>
    'Módulo "{name}" creado. Este módulo tiene, actuamente, la prioridad más baja. Para cambiarla, usa las flechas que hay en cada módulo.',
  'Module "{name}" has been deleted' =>
    'Módulo "{name}" borrado.',
  'Module "{name}" updated' =>
    'Módulo "{name}" actualizado.',
  'Module Status ' =>
    'Estado del Módulo',
  'Module does not exist.' =>
    'El módulo no existe',
  'Modules' =>
    'Módulos',
  'Modules integrated in ' =>
    'Módulos integrados en',
  'Month' =>
    'Mes',
  'Month can not be empty.' =>
    'El mes no puede estar vacío',
  'My profile' =>
    'Mi perfil',
  'My projects' =>
    'Mis proyectos',
  'Name' =>
    'Nombre',
  'New password' =>
    'Nueva contraseña',
  'No license defined' =>
    'No se han encontrado licencias',
  'No modules found. You can create a new one right now!' =>
    'No se han encontrado módulos. Puedes crear uno nuevo ahora mismo.',
  'No projects found. You can create a new one right now!' =>
    'No se han encontrado proyectos. Puedes crear uno nuevo ahora mismo',
  'Now you can log in the application with your user and password.' =>
    'Ahora ya puedes loguearte en la aplicación con tu usuario y contraseña',
  'Oh, dude!! That´s not the way. But you can keep trying.' =>
    'Venga tío! No hagas eso. Pero si quieres, sigue intentándolo.',
  'Old email' =>
    'Email antiguo',
  'Once our project is created, we have to select it so we can add some modules by pressing the "Modules" button.' =>
    'Una vez que has creado el proyecto, tenemos que seleccionarlo para poder añadirle módulos pulsando el botón de "módulos"',
  'Once we are in modules screen, we can create one or edit any we had already created.' =>
    'Cuando estemos en la pantalla de módulos, podremos crear uno o editar cualquiera que hayamos creado.',
  'One of the biggest problems when we perform a compatibility license diagnostic consultancy is access to a clear and detailed list of licenses whose code has been used in development.' =>
    'Uno de los grandes problemas cuando realizamos una consultoría de diagnóstico de compatibilidad de licencias es poder acceder a un listado claro y detallado de las licencias cuyo código ha sido empleado en un desarrollo',
  'Other' =>
    'Otro',
  'Others' =>
    'Otros',
  'PRINT REPORT' =>
    'IMPRIMIR REPORTE',
  'Password' =>
    'Contraseña',
  'Password changed' =>
    'Contraseña cambiada',
  'Pay attention, please!! Check the URL you have just enter. Is it right ? I bet it is not.' =>
    '¡Presta atención, por favor! Revisa la URL que has introducido. ¿Es correcta? No lo creo.',
  'Priority' =>
    'Prioridad',
  'Privacy Policy' =>
    'Política de Privacidad',
  'Privacy policy' =>
    'Política de Privacidad',
  'Privileges' =>
    'Privilegios',
  'Profile' =>
    'Perfil',
  'Profile updated' =>
    'Perfil actualizado',
  'Project' =>
    'Proyecto',
  'Project "{name}" created' =>
    'Proyecto "{name}" creado',
  'Project "{name}" has been deleted' =>
    'Proyecto "{name}" borrado',
  'Project "{name}" updated' =>
    'Proyecto "{name}" actualizado',
  'Project Info' =>
    'Información del proyecto',
  'Project Licenses' =>
    'Licencias del proyecto',
  'Project Modules' =>
    'Módulos del proyecto',
  'Project and licenses editing' =>
    'Edición de licencias y proyectos',
  'Project does not exist.' =>
    'El proyecto no existe',
  'Project modules' =>
    'Módulos del proyecto',
  'Projects' =>
    'Proyectos',
  'Provide a development license choice tool through three criteria: licenses compatibilty, geographical scope and commercial interests.' =>
    'Ofrecer una herramienta de elección de licencia de desarrollo bajo el análisis de tres criterio: Compatibilidad intrínseca de las licencia, Ámbito Geográfico e Intereses comerciales.',
  'Check compatibility between licenses being used' =>
    'Comprobar la compatibilidad de las licencias utilizadas',
  'Re-type password' =>
    'Re-escribe la contraseña',
  'Redirecting to' =>
    'Redireccionando a',
  'Register date' =>
    'Fecha de registro',
  'Registry completed' =>
    'Registro completado',
  'Registry Form' =>
    'Formulario de registro',
  'Relation' =>
    'Relación',
  'Relations' =>
    'Relaciones',
  'Remember' =>
    'Recordar',
  'Remember me next time' =>
    'Recordarme la próxima vex',
  'Remember password' =>
    'Recordar contraseña',
  'Remember password instructions' =>
    'Instrucciones para recuperar la contraseña',
  'Repo' =>
    'Repositorio',
  'Report' =>
    'Reporte',
  'Resend' =>
    'Reenviar',
  'Result' =>
    'Resultado',
  'Right' =>
    'Derecha',
  'Secret' =>
    'Secreto',
  'Secret date' =>
    'Fecha secreta',
  'Select a project' =>
    'Selecciona un proyecto',
  'Set a higher priority' =>
    'Asignar una prioridad más alta',
  'Set a lower priority' =>
    'Asignar una prioridad mas baja',
  'Share projects with other consultants' =>
    'Compartir proyectos con otros consultores',
  'Share this Report' =>
    'Comparte este Reporte',
  'Signup' =>
    'Registrarse',
  'Someone (probably you) has requested a new password for your account.' =>
    'Alguien (probablemente tu) ha solicitado una nueva contraseña para tu cuenta.',
  'Sorry, you do not have enought privileges to perform this action' =>
    'Lo sentimos, no tienes suficientes privilegios para realizar esa acción.',
  'Source code' =>
    'Código fuente',
  'Static' =>
    'Estática',
  'Status' =>
    'Estado',
  'The application comes up from the need for lawyers to be able to access the list of licenses whose code has been integrated into a project development, in order to make an opinion on the licenses compatibility and whether these are in line with business or private interests of our customers.' =>
    'La aplicación surge de la necesidad de los abogados de poder acceder al listado de licencias cuyo código ha sido integrado en un desarrollo, con el objetivo de realizar un dictamen de la compatibilidad de dichas licencias y si estas son acordes a los intereses empresariales o particulares de nuestros clientes.',
  'The compatibility of the modules is determined by the color of the screw.' =>
    'La compatibilidad de los módulos viene determinada por el color de la tuerca.',
  'The first thing we have to do before comparing modules is creating a new project and add some modules so they can be compare.' =>
    'Lo primero que debemos hacer antes de comparar los módulos es crear un nuevo proyecto y añadir algún módulo para que puedan ser comparados.',
  'The modules are created  from bottom to top and that is its priority.' =>
    'Los módulos se crean de abajo hacia arriba y éste orden es el que marca su prioridad.',
  'There are some modules with licenses incompatibility issues:' =>
    'Hay algunos módulos con incompatibilidades de licencias.',
  'There you can see where is the compatibility problem with that module.' =>
    'Ahí podrás ver dónde están los problemas de incompatiblidades con ese módulo.',
  'Therefore we always recommend as a "good practice" to be performed by the companies keep an inventory of such licenses attaching, if possible, the contents thereof by the time the code is linked or integrated.' =>
    'Por ello siempre recomendamos como una “buena práctica” a llevar a cabo por las empresas llevar un inventario de dichas licencias adjuntando, si es posible, el contenido de las mismas en el momento en el que el código es enlazado o integrado.',
  'This is a public link. Anyone may access to your project report so be carefull with whom we share it.' =>
    'Este es un enlace público. Cualquiera podría acceder a él por lo que tenga cuidado a la hora de compartirlo.',
  'This is not a valid date.' =>
    'La fecha no es válida',
  'This module does not belong to selected project.' =>
    'Este módulo no pertenece al proyecto seleccionado.',
  'To confirm this and activate it, go to the following web address:' =>
    ' Para confirmarlo y activarla, sigue el siguiente enlace',
  'To confirm this and have a new password, go to the following web address:' =>
    'Para confirmarlo y obtener una nueva contraseña, sigue el siguiente enlace.',
  'Type' =>
    'Tipo',
  'Types' =>
    'Tipos',
  'Unknown' =>
    'Desconocido',
  'Unnamed' =>
    'Sin nombre',
  'Update' =>
    'Actualizar',
  'Update my profile' =>
    'Actualizar mi perfil',
  'Url' =>
    'Url',
  'User' =>
    'Usuario',
  'Licensium entities' =>
    'Entidades de Licensium',
  'User does not exist.' =>
    'El usuario no existe',
  'Uuid' =>
    'Uuid',
  'View My Projects' =>
    'Ver mis proyectos',
  'View {view} not found' =>
    'Vista {view} no encontrada',
  'We can add a lower or a higher priority by using the arrow provided with each module.' =>
    'Podemos asignarle una prioridad más o menos alta pulsando las flechas que hay en cada módulo.',
  'We can also deactivate the module by pressing the eye icon. This way, that module will not be taken into account in the compatibilty test.' =>
    'También podemos desactivar el módulo pulsando el icono del ojo. De esta forma, el módulo no se tendrá en cuenta a la hora de hacer el test de compatibilidad.',
  'Website' =>
    'Página web',
  'Well done!! Your project has no compatibility problems.' =>
    '¡Enhorabuena! Tu proyecto no tiene ningún problema de incompatibilidad',
  'When we press a module, on the right side of the screen, we will see the module status.' =>
    'Cuando pulsamos un módulo, en la parte derecha de la pantalla, veremos el estado del módulo.',
  'While deleting module "{name}"' =>
    'Mientras se borra el módulo "{name}"',
  'While deleting project "{name}"' =>
    'Mientras se borra el proyecto "{name}"',
  'While this is a task that can be performed easily with the most popular office tools, we wanted to go one step foward and developed a tool that make this work to programmers easier, adding value to the inventory. Licensium has the following features:' =>
    'Si bien esta es una tarea que puede ser realizada de forma sencilla con las herramientas ofimáticas más conocidas, hemos querido ir un paso más allá desarrollando una herramienta que facilite esta labor a los programadores, aportándoles valor a dicho inventario. Licensium ofrece la siguiente funcionalidad:',
  'With Licensium you will be able to:' =>
    'Con Licensium podrás: ',
  'Year' =>
    'Año',
  'Year can not be empty.' =>
    'El año no puede estar vacío',
  'You are about to delete forever one of your modules' =>
    'Estás a punto de borrar para siempre uno de tus módulos.',
  'You are about to delete forever one of your projects.' =>
    'Estás a punto de borrar para siempre uno de tus proyectos.',
  'You are not the owner of this project.' =>
    'No eres el propietario de este proyecto.',
  'You have just created a new account at Licensium.' =>
    'Acabas de crear una nueva cuenta en Licensium',
  'You will receive a confirmation email to validate your account.' =>
    'Recibirás un email de confirmación para validar tu cuenta.',
  'You\'ve been warned but even so you want to delete it, go ahead!' =>
    'Estás advertido pero si aun así quieres borralo, ¡adelante!',
  'Your email is already confirmed' =>
    'Tu email ya ha sido confirmado.',
  'Your email is not confirmed yet! {resend} email confirmation' =>
    '¡Tu email todavía no ha sido confirmado! {resend}',
  'Your password has been changed successfully.' =>
    'Tu contraseña se ha cambiado con éxito.',
  'If you supplied a correct email address and it is signed up in our database, then an email should have been sent to you.' =>
    'Si has escrito un email correcto y está dado de alta en nuestra base de datos, entonces te hemos enviado un correo electrónico.',
  'It contains easy instructions to confirm and complete this password change. If you continue to have difficulty, please contact us:' =>
    'Contiene instrucciones sencillas para confirmar y completar el cambio de contraseña. Si sigues teniendo dificultades, por favor contacta con nosotros:',
  'your email address' =>
    'tu dirección de correo electrónico',
  'your favorite password' =>
    'tu contraseña favorita',
  'your name' =>
    'tu nombre',
  'your last name' =>
    'tus apellidos',
  'the company you are developing software' =>
    'la empresa donde desarrollas software',
  'You must accept our privacy policy' =>
    'Debes aceptar nuestra política de privacidad',
  'Save' =>
    'Guardar',
  'GREEN' =>
    'VERDE',
  'RED' =>
    'ROJO',
  'ORANGE' =>
    'NARANJA',
  'The module is compatible with all of the modules below' =>
    'El módulo es compatible con todos los módulos debajo de él',
  'The module is incompatible with at least one of the modules below' =>
    'El módulo es incompatible con al menos uno de los módulos debajo de él',
  'The status of the compatibility is unknown' =>
    'El estado de compatibilidad es desconocido',
  'A piece of code linked with your program.' =>
    'Porción de código que se enlaza con tu programa',
  'A differentiated block of code that provides a concrete feature.' =>
    'Un bloque diferenciado de código que ofrece una funcionalidad concreta.',
  'A collection of libraries and programming design patterns that helps developers to work faster.' =>
    'Una colección de librerías y patrones de diseño de programación que ayudan a los desarrolladores a trabajar más rápido.',
  'An standalone application that communicates with your project.' =>
    'Una aplicación que se comunica con tu proyecto.',
  'When this piece of code is compiled and linked statically.' =>
    'Cuando esta porción de código se compila y enlaza estáticamente.',
  'When this piece of code is interpreted or linked dinamically.' =>
    'Cuando esta porción de código es interpretada o enlazada dinámicamente.',
  'Confirmation code resent' =>
    'Código de confirmación reenviado',
  'Email updated' =>
    'Correo electrónico actualizado',
  'We use owned and third-party cookies to improve service. If you continue navigating we understand you accept our' =>
    'Utilizamos cookies propias y de terceros para mejorar nuestros servicios. Si continúa navegando entendemos que acepta nuestra',
  'cookies policy' =>
    'política de cookies',
  'Cookies policy' =>
    'Política de cookies',
  'Cookies warning' =>
    'Aviso sobre cookies',
  'Public Domain License' =>
    'Licencia de Dominio Público',
  'The author waives all copyrights (all waivable rights) and grants them to public domain.' =>
    'El autor renuncia a todos sus derechos (renunciables) y los cede al dominio público.',
  'Propietary License' =>
    'Licencia propietaria',
  'We are calling proprietary software license to a license type that does not yield any intellectual property to third parties, beyond the mere use of the program that falls under such license. Opposed to any type of license called open source. Such a license would come to be expressed in the following terms:' =>
    'Le estamos llamando licencia de software propietario a un tipo de licencia que no cede ningún derecho de propiedad intelectual en favor de terceros, más allá del mero uso del programa que cae bajo dicha licencia y en contraposición a cualquier tipo de licencia de las llamadas de código abierto. Una licencia de ese tipo vendría a expresarse en los siguientes términos:',
  'The licensee is granted a nonexclusive, nontransferable license to download, access and use the Software for the sole purpose of using it.' =>
    'Se  otorga al licenciatario un derecho no exclusivo e intransferible para descargar, acceder y usar el Programa con el único fin de utilizarlo para los fines destinados del mismo.',
  'Licensee may not reverse engineer, decompile or disassemble all or part of the Program. Access to the source code in anyway is prohibited.' =>
    'El licenciatario no podrá realizar ingeniería inversa, ni descompilar, ni desensamblar todo o parte del Programa, estando prohibida cualquier forma de acceso al código fuente del mismo.',
  'URL must be absolute, for example, http://licensium.opencodex.es' =>
    'URL debe ser absoluta, por ejemplo, http://licensium.opencodex.es',
//  '' =>
//    '',
);
